name: Hourly File Commit

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  create_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }} # Use PAT instead of default token

      - name: Delete existing .txt files
        run: |
          rm -f *.txt

      - name: Set Time Variables
        run: |
          echo "NOW=$(date +'%d-%m-%Y_%H-%M')" >> $GITHUB_ENV

      - name: Create New File
        run: |
          touch "${{ env.NOW }}.txt"
          echo "File created at $(date)" > "${{ env.NOW }}.txt"

      - name: Commit and Push Changes
        run: |
          RANDOM_NUM=$(shuf -i 1-100 -n 1)
          echo "Random number is $RANDOM_NUM"
          if (( RANDOM_NUM % 2 == 0 )); then
            echo "Random number $RANDOM_NUM is divisible by 2, committing changes..."
            git config --global user.name "Surakat Gideon"
            git config --global user.email "suraktg@gmail.com"
            git add .
            git commit -m "Add file ${{ env.NOW }}.txt" || exit 0
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/lordhynet/projectx.git main
          else
            echo "Random number $RANDOM_NUM is not divisible by 2, skipping commit."
          fi
